### ISSUE TITLE
This tool is not working in Windows

### ISSUE THREAD

**Issue by needtech** [nanjingboy/grunt-css-url-replace#7]
When i run this tool using grunt command it does nothing only shows that output and creating no files

![oup7mkg](https://cloud.githubusercontent.com/assets/8788573/7703779/cf04c0c0-fe57-11e4-8854-27aef4f41f76.png)

// MY GRUNT FILE
module.exports = function(grunt) {

grunt.initConfig({
  css_url_replace: {
    options: {
      staticRoot: 'demotheme'
    },
    files: {
      'css/build.css': ['css\style.css']
    }
  }
});

grunt.loadNpmTasks('grunt-css-url-replace');
  // Default task(s).
  grunt.registerTask('default', ['css_url_replace']);
};

**Comment by nanjingboy** [comment]
hi @needtech, sorry delay sorry long.  Please upgrade this tool and update your Gruntfile like:

```javascript
grunt.initConfig({
  css_url_replace: {
    options: {
      staticRoot: 'demotheme'
    },
    replace: {
      files: {
        'css/build.css': ['css/style.css']
      }
    }
  };
  grunt.loadNpmTasks('grunt-css-url-replace');
  grunt.registerTask('default', ['css_url_replace']);
});
```
